version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
  test:
    machine:
      enabled: true
    steps:
      - checkout
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
