version: 2
jobs:
  build:
    working_directory: ~/jwt_gem
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: git fetch origin master
      - run: git rebase master
      - restore_cache:
          keys:
            - rails-jwt-gem-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-jwt-gem-bundle-v2-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: rails-jwt-gem-service-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: run tests
          command: bundle exec rspec
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
workflows:
  version: 2
  build_rails_and_test:
    jobs:
      - build
